# Generated by Django 3.2.12 on 2023-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('assignment', models.DateTimeField()),
                ('assignment1', models.TimeField()),
                ('assignment2', models.DateField()),
            ],
        ),
    ]
