# Generated by Django 3.2.12 on 2023-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20230222_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='chat_id',
            field=models.PositiveBigIntegerField(verbose_name='ID чата в ТГ'),
        ),
    ]
