# Generated by Django 3.2.12 on 2023-02-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название тарифа')),
                ('request_quantity', models.PositiveSmallIntegerField(verbose_name='Количество заявок')),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'Подрядчик', 'verbose_name_plural': 'Подрядчики'},
        ),
        migrations.AlterField(
            model_name='client',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.tariff', verbose_name='Тариф'),
        ),
    ]
