# Generated by Django 3.2.12 on 2023-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_auto_20230222_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
