# Generated by Django 3.2.12 on 2023-02-22 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_tariff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='requests_left',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 22, 12, 25, 31, 430246), null=True, verbose_name='Дата конца тарифа'),
        ),
    ]
