# Generated by Django 3.2.12 on 2023-02-22 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_auto_20230222_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 22, 13, 46, 13, 164245), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requests_left',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во оставшихся запросов'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название тарифа'),
        ),
    ]
