# Generated by Django 3.2.12 on 2023-02-22 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_auto_20230222_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 22, 16, 36, 37, 901048), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requests_left',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во оставшихся запросов'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 16, 36, 37, 901048), verbose_name='Опубликован')),
                ('put_into_action', models.DateTimeField(blank=True, null=True, verbose_name='Взят в работу')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.client', verbose_name='Клиент')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.freelancer', verbose_name='Подрядчик')),
            ],
        ),
    ]
