# Generated by Django 3.2.12 on 2023-02-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_client_end'),
        ('telegram_bot', '0011_auto_20230222_1636'),
    ]

    operations = [
    ]
