# Generated by Django 4.1 on 2023-02-23 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_auto_20230222_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 23, 16, 24, 7, 948235), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 16, 24, 7, 949243), verbose_name='Опубликован'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Файл к заказу',
                'verbose_name_plural': 'Файлы к заказу',
            },
        ),
    ]
