# Generated by Django 3.2.12 on 2023-02-23 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0017_alter_client_end_alter_order_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_url',
        ),
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 23, 22, 44, 59, 858759), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 22, 44, 59, 858759), verbose_name='Опубликован'),
        ),
    ]
