# Generated by Django 3.2.12 on 2023-02-23 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0018_auto_20230223_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ID в Stripe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 23, 22, 45, 10, 633033), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 22, 45, 10, 633033), verbose_name='Опубликован'),
        ),
    ]
