# Generated by Django 3.2.12 on 2023-02-24 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_auto_20230224_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(default=1, max_length=256, verbose_name='Ссылка на файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dialogue',
            field=models.JSONField(blank=True, null=True, verbose_name='Переписка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 24, 20, 16, 55, 751892), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 20, 16, 55, 751891), verbose_name='Опубликован'),
        ),
    ]
