# Generated by Django 3.2.12 on 2023-02-26 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0027_auto_20230224_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 26, 17, 12, 46, 564475), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dialogue',
            field=models.TextField(blank=True, verbose_name='Переписка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='files',
            field=models.JSONField(default=list, verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 17, 12, 46, 564475), verbose_name='Опубликован'),
        ),
    ]
