# Generated by Django 4.2.7 on 2023-12-02 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0030_auto_20230228_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 2, 21, 45, 41, 158439), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 21, 45, 41, 159488), verbose_name='Опубликован'),
        ),
    ]
